### ISSUE TITLE
Dúvida

### ISSUE THREAD

**Issue by fernote7** [nmecsys/nowcasting#1]
Logo no início da função "nowcast" aparece esse código:

```
  if(is.null(q) & is.null(r) & is.null(p)){
    warnings('Parameters q, r and p must be specified.')
  }

```

Do que eu entendi o texto do warning não condiz com o código escrito. Se para entrar no *if statement* vc exige que os parâmetros q **e** r **e** p sejam não nulos, significa que se um deles não for nulo o statement será pulado. Daí o texto que eu entendo que deveria acompanhar seria "Parameters q, r **or** p must be specified.'"

Depois dá uma olhada nisso. Valeu!

**Comment by guilbran** [comment]
De fato esse detalhe passou pois na condição de apenas um dos parâmetros ser nulo, outros "warnings" apareciam.
Obrigado pela observação. Já foi alterado.
