### ISSUE TITLE
Source code reference

### ISSUE THREAD

**Issue by devon-ge** [nmecsys/nowcasting#3]
I was testing the nowcast function, only to find that there is a function called `EM_DFM_SS_block_idioQARMA_restrMQ` in `Nowcast.R`
https://github.com/nmecsys/nowcasting/blob/7bf63f9d25f15254ec3960f7ab6e651e3b9098e4/R/nowcast.R#L221
Could you tell me how can I read the source code of this function? I may need to change some parameters. Thanks

**Comment by GreedBlink** [comment]
Hello, @devon-ge 

You can access the `EM_DFM_SS_block_idioQARMA_restrMQ` source code  in  
https://github.com/nmecsys/nowcasting/blob/7bf63f9d25f15254ec3960f7ab6e651e3b9098e4/R/method_EM.r#L322

**Comment by GreedBlink** [comment]
Not a problem!
